# Generated by Django 3.2.5 on 2023-01-23 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categoria',
            new_name='Fonte',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='categoria',
            new_name='fonte',
        ),
    ]
