# Generated by Django 3.2.5 on 2023-01-23 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20230123_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='descricao_curta',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='post',
            name='descricao_longa',
            field=models.CharField(max_length=9999),
        ),
        migrations.AlterField(
            model_name='post',
            name='titulo',
            field=models.CharField(max_length=120),
        ),
    ]
