# Generated by Django 3.2.5 on 2023-01-24 02:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20230123_2239'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='criacao',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 24, 2, 8, 36, 793254, tzinfo=utc)),
        ),
    ]
